on: push
name: CI/CD
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: test
      uses: cedrickring/golang-action@1.4.1
      env:
        PROJECT_PATH: "./src"
      with:
        args: go test -v ./...
