on: 
  push:
    branches:
      - master
      - develop
      - 'releases/**'
name: CI/CD
jobs:
  checks:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        uses: actions/setup-go@v5
        env:
          PROJECT_PATH: "./v1"
        with:
          go-version: "==1.22.1"
      - run: "go test -v ./..."
